#!/bin/bash
/root@4cbe70e8d3ac:/alx-system_engineering-devops# cd
0x00-shell_basics
root@4cbe70e8d3ac:/alx-system_engineering-devops/0x00-shell_basics# ls
0-current_working_directory  README.md
root@4cbe70e8d3ac:/alx-system_engineering-devops/0x00-shell_basics#
